version: '3'
services:
  portfolio:
    image: portfolio-website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/archive/celvin.dev:/etc/nginx/certs:ro
    container_name: portfolio
